export const ACTION_TYPES = Object.freeze({
  CHANGE_NUMBER_LEDS: 'CHANGE_NUMBER_LEDS',
  CHANGE_TOTAL_STEPS: 'CHANGE_TOTAL_STEPS',
  CHANGE_SELECTED_COLOR_LEDS: 'CHANGE_SELECTED_COLOR_LEDS',
  CHANGE_TIME_PER_STEP: 'CHANGE_TIME_PER_STEP',
  SELECT_LED: 'SELECT_LED',
  UN_SELECT_LED: 'UN_SELECT_LED',
  MOVE_PLAYER_FORWARD: 'MOVE_PLAYER_FORWARD',
  MOVE_PLAYER_BACKWARD: 'MOVE_PLAYER_BACKWARD',
  CHANGE_POSITION_PLAYER: 'CHANGE_POSITION_PLAYER',
});
